In [131]:
import pandas as pd
from selenium import webdriver as driver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from time import sleep

In [132]:
df = pd.read_excel('challenge.xlsx', header=0, 
                   names=['first_name',
                          'last_name',
                          'company_name',
                          'role_in_company',
                          'address',
                          'email',
                          'phone_number'])

df.head()

,first_name,last_name,company_name,role_in_company,address,email,phone_number
0,John,Smith,IT Solutions,Analyst,98 North Road,jsmith@itsolutions.co.uk,40716543298
1,Jane,Dorsey,MediCare,Medical Engineer,11 Crown Street,jdorsey@mc.com,40791345621
2,Albert,Kipling,Waterfront,Accountant,22 Guild Street,kipling@waterfront.com,40735416854
3,Michael,Robertson,MediCare,IT Specialist,17 Farburn Terrace,mrobertson@mc.com,40733652145
4,Doug,Derrick,Timepath Inc.,Analyst,99 Shire Oak Road,dderrick@timepath.co.uk,40799885412

In [133]:
driver = driver.Chrome()
driver.get('https://rpachallenge.com/')

In [ ]:
for i in df.itertuples(index=None):
    first_name = i.first_name
    last_name = i.last_name
    company_name = i.company_name
    role_in_company = i.role_in_company
    phone_number = i.phone_number
    address = i.address
    email = i.email

    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelFirstName"]').send_keys(first_name)
    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelRole"]').send_keys(role_in_company)
    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelLastName"]').send_keys(last_name)
    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelCompanyName"]').send_keys(company_name)
    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelPhone"]').send_keys(phone_number)
    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelEmail"]').send_keys(email)
    driver.find_element(By.XPATH,'//*[@ng-reflect-name="labelAddress"]').send_keys(address)

    sleep(0.5)
    driver.find_element(By.XPATH,'/html/body/app-root/div[2]/app-rpa1/div/div[2]/form/input').click()
    sleep(1)